use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let shipped_dir = Path::new(&manifest_dir).join("levels").join("shipped");
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_shipped_levels.rs");

    println!("cargo:rerun-if-changed=levels/shipped");

    let mut level_entries = Vec::new();

    if shipped_dir.exists() {
        collect_levels(&shipped_dir, &shipped_dir, &mut level_entries);
    }

    // Sort deterministically by folder then filename
    level_entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — DO NOT EDIT MANUALLY\n\n");
    code.push_str("#[derive(Clone, Debug)]\n");
    code.push_str("pub struct EmbeddedLevel {\n");
    code.push_str("    pub rel_path: &'static str,\n");
    code.push_str("    pub folder: &'static str,\n");
    code.push_str("    pub filename: &'static str,\n");
    code.push_str("    pub json: &'static str,\n");
    code.push_str("}\n\n");
    code.push_str("pub static EMBEDDED_SHIPPED_LEVELS: &[EmbeddedLevel] = &[\n");

    for (rel_path, folder, filename, include_path) in level_entries {
        code.push_str("    EmbeddedLevel {\n");
        code.push_str(&format!("        rel_path: {:?},\n", rel_path));
        code.push_str(&format!("        folder: {:?},\n", folder));
        code.push_str(&format!("        filename: {:?},\n", filename));
        code.push_str(&format!(
            "        json: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {:?})),\n",
            include_path
        ));
        code.push_str("    },\n");
    }

    code.push_str("];\n");

    fs::write(dest_path, code).unwrap();
}

fn collect_levels(base_dir: &Path, current_dir: &Path, entries: &mut Vec<(String, String, String, String)>) {
    if let Ok(read_dir) = fs::read_dir(current_dir) {
        for entry in read_dir.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_levels(base_dir, &path, entries);
            } else if path.extension().and_then(|s| s.to_str()) == Some("json") {
                if let Ok(rel) = path.strip_prefix(base_dir) {
                    let rel_path_str = rel.to_string_lossy().replace('\\', "/");
                    let folder_str = rel
                        .parent()
                        .map(|p| p.to_string_lossy().replace('\\', "/"))
                        .unwrap_or_default();
                    let filename_str = rel
                        .file_name()
                        .map(|f| f.to_string_lossy().to_string())
                        .unwrap_or_default();

                    // Relative path from manifest root: /levels/shipped/...
                    let include_path = format!("/levels/shipped/{}", rel_path_str);
                    entries.push((rel_path_str, folder_str, filename_str, include_path));
                }
            }
        }
    }
}
